stages:
  - test

test_job:
  stage: test
  image: debian:unstable
  script:
    - apt-get update
    - apt-get install -y storm-lang
    - storm -i root/http -T http
  only:
    - master
    - merge_requests
