void arrays() {
	Nat[] numbers = [0, 1];
	for (Nat i = 2; i < 15; i++) {
		numbers << numbers[i - 1] + numbers[i - 2];
	}

	for (k, v in numbers) {
		print("${k,2}: ${v,3}");
	}

	print(join(numbers, " -> ").toS);
}


void maps() {
	Nat current = 0;
	Nat next = 1;
	for (Nat i = 0; i < 10; i++) {
		print("fib(${i,2}) is: ${current,5}");
		Nat sum = current + next;
		current = next;
		next = sum;
	}
}
