use core:lang;
use core:io;
use lang:bs:macro;

void eval(Str expr) on Compiler {
    Parser<SHeaders> parser;
    parser.parse(expr, Url());
    Str->Str headers;
    SHeaders tree = parser.tree();
    tree.transform(headers);
    // print(parser.infoTree().format());
    print(headers.toS());
    // IDEA: Traverse the tree in .bs code
    // IDEA: Pass a map as a parameter and call put
    // IDEA: Construct intermediary Map<Str, Str> see:
    // https://storm-lang.org/Getting_Started/Tutorials/Using_Grammar.html
    // § "In the end, the new grammar we added to the file is the following:"
}

void main() {
    eval("User-Agent: Mozilla/4.0 (compatible; MSIE5.01; Windows NT)\r\nHost: www.tutorialspoint.com\r\nAccept-Language: en-us\r\nAccept-Encoding: gzip, deflate\r\nConnection: Keep-Alive\r\n\r\n");
}
