optional delimiter = SOptDelimiter;
required delimiter = SReqDelimiter;

void SOptDelimiter();
SOptDelimiter : "";

void SReqDelimiter();
SReqDelimiter : " ";

void SHeaders();
SHeaders : SHeader, (SCRLF, SHeader)*, SCRLF, SCRLF;

void SHeader();
SHeader : SFieldName, ":" ~ SFieldValue;

void SFieldName();
SFieldName : "[a-zA-Z0-9\-]+";

void SFieldValue();
SFieldValue : "[a-zA-Z0-9\-/.() ;,]+";

void SCRLF();
SCRLF : "\r\n";
