use lang:bs:effects;
use lang:bs:macro;
use test;

effect: Int myEffect(Int x);

handler: Float MyHandler(Int) {
	myEffect(Int x), k {
		print("In handler, x = ${x}");
		Float r = k.call(x + 10) + 0.5;
		print("Returning ${r}");
		r;
	}
	return x {
		print("In return handler: ${x}");
		(x + 1).float;
	}
}

suite Basic {
	Float w = handle {
		Int x = myEffect(1);
		print("x = ${x}");
		Int y = myEffect(x + 100);
		print("y = ${y}");
		y;
	} with MyHandler;

	test w == 123.0;
	print("Result: ${w}");
}
