use core:debug;

Int returnInt(Int v) {
	if (v > 20) {
		return 20;
	}

	10;
}

Int returnAlways(Int v) {
	return v;
}

Str returnStr(Int v) {
	if (v > 20) {
		return v.toS;
	}

	"no";
}

DbgVal returnDbgVal(Int v) {
	if (v > 20) {
		return DbgVal(20);
	}

	DbgVal(10);
}

Int deduceType(Int v) {
	if (v > 20) {
		return 22;
	} else {
		3;
	}
}


Int prematureReturn(Int v) {
	return v + 10;
	10.3;
}


Int inlineReturnFn(Int x) : inline {
	if (x > 10)
		return 8;
	else
		return 2;
}

Int inlineReturn(Int x) {
	Int y = inlineReturnFn(x);
	y + 10;
}
