class ScopeCls {
	Int v;

	init() {
		init() { v = 20; }
	}

	Int get() {
		Int v = 10;
		v;
	}

	Int testScope() {
		tester();
	}

	Int testScopeNoDot() {
		tester(this);
	}

	Int testScopeNoThis() {
		noThis();
	}

	Str testClassCollision() {
		classCollision.toS;
	}

	Int tester() {
		v;
	}

	Int noThis() {
		v;
	}

	Int classCollision() {
		0;
	}
}

Int tester(ScopeCls s) {
	10;
}

Int noThis() {
	10;
}

class classCollision {
	init() {}

	Str toS() : override {
		return "class";
	}
}

Int testScopeCls() {
	ScopeCls c;
	c.get;
}


Int testClassMember() {
	ScopeCls c;
	c.testScope;
}

Int testClassNonmember() {
	ScopeCls c;
	c.tester;
}

Int testClassNonmemberNoDot() {
	ScopeCls c;
	// Note: Equivalent to c.tester().
	tester(c);
}

Int testClassMemberNoDot() {
	ScopeCls c;
	c.testScopeNoDot();
}

Int testClassNoThis() {
	ScopeCls c;
	c.testScopeNoThis();
}

Str testClassCollision() {
	ScopeCls c;
	c.testClassCollision();
}
