class ScopeCls {
	Int v;

	init() {
		init() { v = 20; }
	}

	Int get() {
		Int v = 10;
		v;
	}

	Int testScope() {
		tester();
	}

	Int testScopeNoDot() {
		// Note: due to equivalence of this.tester() and tester(this), this matches the member
		// function since that one is closer in scope.
		tester(this);
	}

	Int testScopeNoThis() {
		noThis();
	}

	Str testClassCollision() {
		classCollision.toS;
	}

	Int tester() {
		v;
	}

	Int noThis() {
		v;
	}

	Int classCollision() {
		0;
	}
}

Int tester(ScopeCls s) {
	10;
}

Int noThis() {
	10;
}

class classCollision {
	init() {}

	Str toS() : override {
		return "class";
	}
}

Int testScopeCls() {
	ScopeCls c;
	c.get;
}


Int testClassMember() {
	ScopeCls c;
	c.testScope;
}

Int testClassNonmember() {
	ScopeCls c;
	c.tester;
}

Int testClassNonmemberNoDot() {
	ScopeCls c;
	// Note: since we don't have explicit c.tester(), the 'tester' function is a better match since
	// it is closer to us.
	tester(c);
}

Int testClassMemberNoDot() {
	ScopeCls c;
	c.testScopeNoDot();
}

Int testClassNoThis() {
	ScopeCls c;
	c.testScopeNoThis();
}

Str testClassCollision() {
	ScopeCls c;
	c.testClassCollision();
}
