use lang.bs;

optional delimiter = SDelimiter;
required delimiter = SRequiredDelimiter;

SExpr => MapExpr(pos, block, src, var) : "map" #keyword, "(", SExpr(me) -> setTransform ~ "for" #keyword ~ SName var #varName ~ "in" #keyword ~ SExpr(block) src, ")";
