use lang.bs;

optional delimiter = SDelimiter;
required delimiter = SRequiredDelimiter;

SFileItem => Template(pos, env, params, body) : "template" #keyword, "<", STemplateList params, ">", SFileItem @body;


Array<TemplateParam> STemplateList();
STemplateList => Array<TemplateParam>() : ;
STemplateList => Array<TemplateParam>() : STemplateElem -> push - (, ",", STemplateElem -> push)*;

TemplateParam STemplateElem();
STemplateElem => TemplateParam(name.v) : SName name;
