#!/bin/bash

echo "Building documentation..."

if [[ $# -lt 2 ]]
then
    echo "Expected <version> <date>"
    exit 1
fi
version=$1
date=$2

mm Main -ne || exit 1

echo "Generating html..."
release-notes > doc/release_notes.txt
messages=$(debug/Storm -f markdown.doc.generateStormDoc -- --version=${version} --date=${date} --clear html 2>&1)
result=$?


messages=$(echo "$messages" | grep -vE '^(Loading documentation from|Removing contents of|Generating output to|Done!).*$')

if [[ "$messages" == "" && $result == 0 ]]
then
    echo "Documentation for ${version}, ${date} built successfully!"
    (cd html/; tar czf ${STORM_ROOT}/release/doc.tar.gz .)
    exit 0
else
    echo "Errors while building documentation:"
    echo "$messages"
    exit 1
fi
