#!/bin/bash

# Launchers to include in build: (space separated)
launchers="progvis.main"

OUT_BASE=$STORM_ROOT/release/storm

# Architecture
arch="$1"

if [[ $arch == win* ]]
then
    OUT_EXT=.zip
    add="7z a"
    exe=".exe"
    lib=".dll"
    scr=".bat"
else
    OUT_EXT=.tar
    add="tar -rf"
    exe=""
    lib=".so"
    scr=".sh"
fi
OUT=$OUT_BASE$OUT_EXT

notes="$2"

function launcher {
    if [[ "$2" =~ \.bat$ ]]
    then
	echo "@%~dp0Storm.exe -f $1" > "$2"
    else
	(
	    echo '#!/bin/bash'
	    echo 'DIR=$(dirname "$0")'
	    echo 'chmod +x "$DIR"/Storm'
	    echo "\"\$DIR\"/Storm -f $1"
	) > "$2"
	chmod +x "$2"
    fi
}

function add_rename {
    cp $1 $2
    eval $add $OUT $2 > /dev/null
    rm $2
}

function add_rename_custom {
    cp $2 $3
    eval $add $1 $3 > /dev/null
    rm $3
}

if [[ -e $OUT ]]
then
    rm $OUT
fi

cd $STORM_ROOT

echo "Packing release..."

# Documentation.
find doc/ -type f | xargs --delimiter='\n' $add $OUT > /dev/null

# Release notes.
if [[ -f $notes ]]
then
    cp "$notes" doc/release_notes.md
else
    release-notes > doc/release_notes.md
fi

$add $OUT doc/release_notes.md > /dev/null
rm doc/release_notes.md

# Source code.
find root/ -type f -not -name "*$lib" | grep -v "server-tests/" | xargs --delimiter='\n' $add $OUT > /dev/null

# Rename and add dynamic libraries
IFS=$'\n'
for j in $(find root/ -name "Release*$lib")
do
    name=$(echo $j | sed 's/Release//')
    add_rename $j $name
done

# Add the Emacs plugin.
add_rename Plugin/emacs.el storm-mode.el


# Add any launchers.
for l in $launchers
do
    name=${l%%.*}$scr
    name=${name^} # upcase first letter
    launcher "$l" "$name"
    eval $add $OUT "$name" > /dev/null
    rm "$name"
done


# Copy the file to two separate ones, one for each release:
cp $OUT ${OUT_BASE}_mps_$arch$OUT_EXT
mv $OUT ${OUT_BASE}_smm_$arch$OUT_EXT

# Add the main executables
add_rename_custom ${OUT_BASE}_mps_$arch$OUT_EXT release/Storm_mps$exe Storm$exe
add_rename_custom ${OUT_BASE}_smm_$arch$OUT_EXT release/Storm_smm$exe Storm$exe

if [[ $OUT_EXT == .tar ]]
then
    if [[ -e ${OUT_BASE}_mps_$arch.tar.gz ]]
    then
	rm ${OUT_BASE}_mps_$arch.tar.gz
    fi
    if [[ -e ${OUT_BASE}_smm_$arch.tar.gz ]]
    then
	rm ${OUT_BASE}_smm_$arch.tar.gz
    fi

    gzip ${OUT_BASE}_mps_$arch.tar
    gzip ${OUT_BASE}_smm_$arch.tar
fi

echo "Done!"
