#!/bin/bash

echo "Checking documentation..."

echo tmp > notes.txt
mm Main -ne
messages=$(debug/Storm -f markdown.doc.generateStormDoc -- --version=0.0 --date=0000-00-00 --notes=notes.txt --clear html 2>&1)
result=$?
rm notes.txt

messages=$(echo "$messages" | grep -vE '^(Loading documentation from|Removing contents of|Generating output to|Done!).*$')

if [[ "$messages" == "" && $result == 0 ]]
then
    echo "Documentation is OK!"
else
    echo "Errors while building documentation:"
    echo "$messages"
    exit 1
fi

