use test;
use markdown;

suite BasicMarkdown {
	var simple = str {
		this is a
		paragraph

		this is the
		next *paragraph*
		with four
		lines

		single line

		this is a heading
		=================

		### deep heading

		this is another paragraph
	};

	var result = parse(simple + "\n");
	if (v = result.value) {
		print("Result:");
		print(v.toS);
		print(v.toHtml.toS);
	} else {
		print("Error: ${result.error}");
	}
	// print(result.toS);
}
