use lang.bnf;

optional delimiter = SDelim;
required delimiter = SReqDelim;

SFileItem => BsProductionDecl(pos, member, parent, body)
  : SParentReq parent, SName member, SPriority -> pushPrio
    [, ":", SRepIndentTokens(me) - SProdName(me)]+, lang.bs.SBlock @body;
