use core:net;
use core:io;
use http;

void main(){
  //Listener? socket = listen(1234, true);
  //unless(socket){
   // print("Error! Cannot bind socket.");
   // return;
  //}
  HTTP_Server server(1234);


  while(true){
    HTTP_Request req = server.recieve();
    //Read requests here...
    print("\n\nRecieved the following request:");
    print("Method: ${req.method}");
    print("HTTP Version: ${req.version}");
    print("Path: ${req.path.toS()}");
    print("\nMethod parameters:");
    for(k, v in req.method_params){
      print("${k} : ${v}");
    }
    HTTP_Response res;
    //TODO skapa header tests Fille o/c.
    res.version = HTTP_Version:HTTP_1_1;
    res.status_code = HTTP_StatusCode:OK;
    
    //res.headers.types.push(HTTP_Header_Type:Content_Length);
    // res.headers.contents.push("132");

    res.headers.put("content-type", "text/html; charset=utf-8");
    //res.headers.contents.push("text/html; charset=utf-8");

    res.headers.put("connection", "close");

    //TODO, don't hardcode the website in "send on the http server"
    //res.headers.contents.push("close");

    server.send(res);
  }
}
