use http;
use core:io;

/* TODO(Christoffer): Use the testing framework */
void main(){
  print("Creating Server");
  //HTTP_Server server;
  print("Creating Server");

  HTTP_Parser parser;
  Buffer testbuf;
  testbuf = "GET /resources/hello.htm?banana=true&feet=big HTTP/1.1\r\nUser-Agent: Mozilla/4.0 (compatible; MSIE5.01; Windows NT)\r\nHost: www.tutorialspoint.com\r\nAccept-Language: en-us\r\nAccept-Encoding: gzip, deflate\r\nConnection: Keep-Alive\r\n\r\n".toUtf8();

  HTTP_Request req = parser.parse_request(testbuf);
  if (req.method != HTTP_Method:GET) {
    print("TEST FAILED");
  }
  if (req.path != parsePath("/resources/hello.htm")) {
    print("TEST FAILED");
  }
  if (req.version != HTTP_Version:HTTP_1_1) {
    print("TEST FAILED");
  }

  print("Creating request");
  HTTP_Request request;
  print("Creating response");
  HTTP_Response response;

  response.status_code = HTTP_StatusCode:OK;

  print("Namespace (tm)");
}
