use test;
use http;
use core:io;
/*
 * Körs mha `Storm -T http`
 */

/* GET */
suite ParseFullGet {
  Str teststr;
  teststr = "GET /resources/hello.htm?banana=true&feet=big HTTP/1.1\r\nUser-Agent: Mozilla/4.0 (compatible; MSIE5.01; Windows NT)\r\nHost: www.tutorialspoint.com\r\nAccept-Language: en-us\r\nAccept-Encoding: gzip, deflate\r\nConnection: Keep-Alive\r\n\r\n";
  HTTP_Request req = parse_request(teststr);
  test req.method == HTTP_Method:GET;
  test req.path == parsePath("/resources/hello.htm");
  test req.version == HTTP_Version:HTTP_1_1;
  test req.method_params["banana"] == "true";
  test req.method_params["feet"] == "big";
  // test req.headers.types[0] == HTTP_Header_Type:User_Agent;
  // test req.headers.contents[0] == "Mozilla/4.0 (compatible; MSIE5.01; Windows NT)";
  // test req.headers.types[1] == HTTP_Header_Type:Host;
  // test req.headers.contents[1] == "www.tutorialspoint.com";
  // test req.headers.types[2] == HTTP_Header_Type:Accept_Language;
  // test req.headers.contents[2] == "en-us";
  // test req.headers.types[3] == HTTP_Header_Type:Accept_Encoding;
  // test req.headers.contents[3] == "gzip, deflate";
  // test req.headers.types[4] == HTTP_Header_Type:Connection;
  // test req.headers.contents[4] == "Keep-Alive";
  test req.data.fromUtf8 == "";
}

suite ParseRootPath {
  Str teststr;
  teststr = "GET /?key1=val1&key2=val2 HTTP/1.1\r\n\r\n";
  HTTP_Request req = parse_request(teststr);
  test req.path == parsePath("/");
  test req.method_params["key1"] == "val1";
  test req.method_params["key2"] == "val2";
}

suite ParseNoHeaders {
  Str teststr;
  teststr = "GET /resources/hello.htm?banana=true&feet=big HTTP/1.1\r\n\r\n";
  HTTP_Request req = parse_request(teststr);
  // test req.headers.types.count == 0;
  // test req.headers.contents.count == 0;
}

suite ParseNoQueryParams {
  Str teststr;
  teststr = "GET /resources/hello.htm HTTP/1.1\r\nUser-Agent: Mozilla/4.0 (compatible; MSIE5.01; Windows NT)\r\nHost: www.tutorialspoint.com\r\nAccept-Language: en-us\r\nAccept-Encoding: gzip, deflate\r\nConnection: Keep-Alive\r\n\r\n";
  HTTP_Request req = parse_request(teststr);
  test req.method_params.count == 0;
}

/* POST */
suite ParseFullPost {
  Str teststr;
  teststr = "POST /submit-form HTTP/1.0\r\nUser-Agent: Mozilla/5.0\r\nHost: www.example.com\r\nContent-Type: application/x-www-form-urlencoded\r\nContent-Length: 48\r\n\r\nusername=bobbytables&name=robert&city=EAS&age=39";
  HTTP_Request req = parse_request(teststr);
  test req.method == HTTP_Method:POST;
  test req.path == parsePath("/submit-form");
  test req.version == HTTP_Version:HTTP_1_0;
  test req.method_params.count == 0;
  // test req.headers.types[0] == HTTP_Header_Type:User_Agent;
  // test req.headers.contents[0] == "Mozilla/5.0";
  // test req.headers.types[1] == HTTP_Header_Type:Host;
  // test req.headers.contents[1] == "www.example.com";
  // test req.headers.types[2] == HTTP_Header_Type:Content_Type;
  // test req.headers.contents[2] == "application/x-www-form-urlencoded";
  // test req.headers.types[3] == HTTP_Header_Type:Content_Length;
  // test req.headers.contents[3] == "48";
  test req.data.fromUtf8 == "username=bobbytables&name=robert&city=EAS&age=39";
}
